#!/bin/bash

if [ "$1" == "--setup" ]; then
    ABS_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/$(basename "${BASH_SOURCE[0]}")"
    (crontab -l | grep -v $(basename "$0"); echo "2-59/3 * * * * $ABS_PATH") | crontab -
    exit 0
fi

INST_ID=$(ec2metadata --instance-id)
INST_TYPE=$(ec2metadata --instance-type)
AVAIL_ZONE=$(ec2metadata --availability-zone)
REGION=${AVAIL_ZONE::-1}

df -k -l --type=ext4 -P | grep ^/ | while read -r line; do
    VOL_UTIL_PERC=$(echo $line | cut -d' ' -f5 | tr -d '%')
    MOUNT=$(echo $line | cut -d' ' -f6)
    aws cloudwatch put-metric-data --region $REGION --metric-name DiskSpaceUtilization --namespace Custom/EC2 --unit Percent --value $VOL_UTIL_PERC --dimensions InstanceId=$INST_ID,InstanceType=$INST_TYPE,AvailabilityZone=$AVAIL_ZONE,Mount=$MOUNT
done

MEMINFO=$(free -m | grep Mem)
MEM_TOTAL=$(echo $MEMINFO | cut -d' ' -f2)
MEM_AVAIL=$(( 100 * $(echo $MEMINFO | cut -d' ' -f7) ))
MEM_AVAIL_PERC=$(($MEM_AVAIL / $MEM_TOTAL))
MEM_UTIL_PERC=$((100 - $MEM_AVAIL_PERC))
aws cloudwatch put-metric-data --region $REGION --metric-name MemoryUtilization --namespace Custom/EC2 --unit Percent --value $MEM_UTIL_PERC --dimensions InstanceId=$INST_ID,InstanceType=$INST_TYPE,AvailabilityZone=$AVAIL_ZONE
